# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f6712ad49b539f4ebadcb4fd762afe9032d5209c147d726bcba6a412995985c3ec39fd3b8c592654c6699509f8356ee4f6dece8aa4d8e5a5e879f7511fbf90

test:
  secret_key_base: 5f6898024697d3faf00a7d15082b1899e08c168024a3da372650b89eb66dbb48e352ac9ba112e0c58a6eddbc379a6363ca9287a36c841f0767977720167d86bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
